Техническое задание. Часть 1
MrOlegBar/java-shareit pull request #1
Opened 2023-02-08 14:11 UTC by MrOlegBar

2023-02-08 19:36 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User userFromDto = userMapper.toUser(userDto);
изменить пользователя можно только один раз. Во второй раз система пишет {
	"error": "Пользователь с email: wrong_emai@lmail.com уже существует."
}
Получается нельзя обновить пользователю только логин, например.

2023-02-08 19:50 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Нашел только одно замечание

2023-02-08 19:53 UTC, MrOlegBar commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User userFromDto = userMapper.toUser(userDto);
Исправил

2023-02-08 19:55 UTC, MrOlegBar commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        User userFromDto = userMapper.toUser(userDto);
Поторопился)не исправил

2023-02-09 16:13 UTC, EvgenyKoptubenko approved these changes
Работа сделана отлично. Спасибо.

2023-02-15 13:07 UTC, merged