Проект ShareIt. Техническое задание. Часть 3
MrOlegBar/java-shareit pull request #3
Opened 2023-03-16 18:16 UTC by MrOlegBar

2023-03-18 20:54 UTC, EvgenyKoptubenko commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
Можно не писать слово public на каждом тесте

2023-03-18 20:55 UTC, EvgenyKoptubenko commented
Тестов целая куча. Если есть желание, попробуй сделать какие-то из них параметризованными, чтобы сократить количество кода
https://www.baeldung.com/parameterized-tests-junit-5

2023-03-18 20:59 UTC, EvgenyKoptubenko requested changes
Работа сделана отлично. Есть предложение попробовать параметризованные тесты, если есть желание

2023-03-19 13:04 UTC, MrOlegBar commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
Я и не писал) При создании класса он сам добавляется. Забыл про создание тестов через Generate

2023-03-19 13:05 UTC, MrOlegBar commented
> Тестов целая куча. Если есть желание, попробуй сделать какие-то из них параметризованными, чтобы сократить количество кода https://www.baeldung.com/parameterized-tests-junit-5

Желание есть времени нет.  Я попробовал на паре тестовых классов - классная штука.

2023-03-19 19:51 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-19 21:33 UTC, merged